on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 🔨 Build Project
        run: |
          cd frontend
          npm ci
          npm run build --if-present
        env:
          CI: false

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER}}
          password: ${{ secrets.FTP_PASSWORD}}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
          dangerous-clean-slate: true
          local-dir: build/
