on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 🔨 Build Project
        run: |
          cd frontend
          npm i --force
          npm run build --if-present

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER}}
          password: ${{ secrets.FTP_PASSWORD}}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
          local-dir: ./frontend/build/

      - name: 🔨 Build Api
        uses: ./backend/
        run: |
          git pull
          npm ci

      - name: 📂 Sync Api files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_API}}
          password: ${{ secrets.FTP_PASSWORD}}
          exclude: |
            **/.git*
            **/.env*
            **/.git*/**
            **/node_modules/**
          local-dir: ./backend/
